/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (database reachable) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready to serve */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create owner account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupRequest"];
                };
            };
            responses: {
                /** @description Session established */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or admin login (role in token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token; issue new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description New session pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke refresh tokens on the server; client still discards local tokens
         * @description Accepts either a bearer access token (revokes every refresh family for the user) or a JSON body `{refresh_token}` without a bearer token (revokes only that token's family). The body form lets a web BFF revoke after the short-lived access token has expired. Supplying neither is 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Verified */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate-limited resend */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted if applicable */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Always generic success */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Password changed; refresh tokens revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register push token (unused for campaigns in MVP) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        platform: "ios" | "android";
                    };
                };
            };
            responses: {
                /** @description Stored */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    include_archived?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Garage list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Vehicle"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleWrite"];
                };
            };
            responses: {
                /** @description Created (or idempotent replay) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vehicle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VehiclePatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-delete vehicle and hide child records */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set as the user's active vehicle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active vehicle updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read model for Dashboard (screen 3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/plan-items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["PlanItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanItemWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanItem"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/suggested-plan-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog filtered by vehicle fuel_type */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Templates (not yet user-owned) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["SuggestedPlanItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-items/{planItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planItemId: components["parameters"]["planItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable or delete user copy; history remains on service records */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planItemId: components["parameters"]["planItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planItemId: components["parameters"]["planItemId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PlanItemPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanItem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/service-records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description History newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["ServiceRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceRecordWrite"];
                };
            };
            responses: {
                /** @description Created; vehicle mileage may increase */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRecord"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-records/{serviceRecordId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceRecordId: components["parameters"]["serviceRecordId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serviceRecordId: components["parameters"]["serviceRecordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRecord"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serviceRecordId: components["parameters"]["serviceRecordId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ServiceRecordWrite"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRecord"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["DocumentCategory"];
                };
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vault list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Document"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DocumentWrite"];
                };
            };
            responses: {
                /** @description Metadata created; upload bytes to /media */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["documentId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: components["parameters"]["documentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: components["parameters"]["documentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: components["parameters"]["documentId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DocumentPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["ExpenseCategory"];
                };
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Expense"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/expenses/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Month, total, optional category breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: components["parameters"]["expenseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    expenseId: components["parameters"]["expenseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    expenseId: components["parameters"]["expenseId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExpenseWrite"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        /** Per-vehicle parts catalog (name A–Z) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Parts list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Part"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a part; no delete in this slice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartWrite"];
                };
            };
            responses: {
                /** @description Created (or idempotent replay) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Part"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partId: components["parameters"]["partId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partId: components["parameters"]["partId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Part"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/fuel-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account fuel types catalog */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["FuelCatalogType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a fuel type; no delete in this slice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FuelCatalogTypeWrite"];
                };
            };
            responses: {
                /** @description Created (or idempotent replay) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FuelCatalogType"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fuel-types/{fuelTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fuelTypeId: components["parameters"]["fuelTypeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fuelTypeId: components["parameters"]["fuelTypeId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FuelCatalogTypePatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FuelCatalogType"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/vehicles/{vehicleId}/fuel-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["vehicleId"];
            };
            cookie?: never;
        };
        /** Refuel or charge logs for the vehicle */
        get: {
            parameters: {
                query?: {
                    fuel_type_id?: string;
                    month?: "this_month" | "all";
                };
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["FuelLog"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Log a refuel or charge; no delete in this slice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: components["parameters"]["vehicleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FuelLogWrite"];
                };
            };
            responses: {
                /** @description Created (or idempotent replay) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FuelLog"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fuel-logs/{fuelLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fuelLogId: components["parameters"]["fuelLogId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fuelLogId: components["parameters"]["fuelLogId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Log */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FuelLog"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fuelLogId: components["parameters"]["fuelLogId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FuelLogPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FuelLog"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description In-app feed newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Notification"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: components["parameters"]["notificationId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "unread" | "read" | "done" | "dismissed";
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload bytes (multipart). Max 15MB after client compression. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: uuid
                         * @description Client media UUID
                         */
                        id: string;
                        /** Format: binary */
                        file: string;
                        /** @enum {string} */
                        purpose?: "vehicle_photo" | "document" | "service_receipt" | "expense_receipt";
                    };
                };
            };
            responses: {
                /** @description Stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MediaObject"];
                    };
                };
                413: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect or JSON with short-lived download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mediaId: components["parameters"]["mediaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metadata + url */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MediaObject"];
                    };
                };
                /** @description Optional redirect to signed URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drain a batch of outbox operations in order */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncPushRequest"];
                };
            };
            responses: {
                /** @description Per-item results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPushResponse"];
                    };
                };
                401: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull change log after cursor */
        get: {
            parameters: {
                query: {
                    /** @description Opaque. Empty string on first pull. */
                    cursor: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of changes plus next cursor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPullResponse"];
                    };
                };
                /** @description Cursor rejected — client should full-snapshot once */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts and recent activity (no fuel/insurance KPIs) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminDashboard"];
                    };
                };
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Search email or name */
                    q?: string;
                    status?: "active" | "deactivated";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["AdminUserListItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile (no document bytes) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserProfile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Support plan change */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        plan?: components["schemas"]["Plan"];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserProfile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/users/{userId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserProfile"];
                    };
                };
                /** @description Last remaining admin */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserProfile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/send-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Same mail flow as owner forgot-password */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    type?: components["schemas"]["PartnerType"];
                    status?: components["schemas"]["PartnerStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partners */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Partner"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnerWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partner"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{partnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: components["parameters"]["partnerId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: components["parameters"]["partnerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partner */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partner"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: components["parameters"]["partnerId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerWrite"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partner"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "ready";
        };
        ErrorBody: {
            error: {
                /** @example mileage_decrease */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        Plan: "free" | "premium";
        /** @enum {string} */
        Role: "owner" | "admin";
        /** @enum {string} */
        AccountStatus: "active" | "deactivated";
        /** @enum {string} */
        FuelType: "petrol" | "electric" | "hybrid_plugin";
        /** @enum {string} */
        DocumentCategory: "insurance" | "registration" | "invoice" | "warranty" | "receipt" | "other";
        /** @enum {string} */
        ExpenseCategory: "fuel" | "maintenance" | "insurance" | "parking" | "tolls" | "parts" | "other";
        /** @enum {string} */
        PartnerType: "workshop" | "insurer";
        /** @enum {string} */
        PartnerStatus: "draft" | "pending_verification" | "verified" | "rejected";
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        SessionResponse: {
            access_token: string;
            refresh_token: string;
            /** @description Access TTL seconds */
            expires_in?: number;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            display_name?: string | null;
            role: components["schemas"]["Role"];
            plan: components["schemas"]["Plan"];
            status: components["schemas"]["AccountStatus"];
            email_verified: boolean;
            /** Format: uuid */
            active_vehicle_id?: string | null;
            /** @description 1 for free, null for unlimited premium (gating off in MVP) */
            vehicle_limit?: number | null;
            /** Format: date-time */
            created_at?: string;
        };
        UserPatch: {
            display_name?: string;
            /** Format: uuid */
            active_vehicle_id?: string;
        };
        Vehicle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            nickname?: string | null;
            make: string;
            model: string;
            year: number;
            license_plate: string;
            vin?: string | null;
            color?: string | null;
            fuel_type: components["schemas"]["FuelType"];
            /** Format: double */
            mileage: number;
            /**
             * @default mi
             * @enum {string}
             */
            mileage_unit: "mi" | "km";
            /** Format: date */
            purchase_date?: string | null;
            purchase_price?: number | null;
            /** Format: uuid */
            photo_media_id?: string | null;
            archived: boolean;
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: date-time */
            updated_at?: string;
            next_maintenance?: components["schemas"]["NextMaintenance"];
        };
        VehicleWrite: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["VehiclePatch"];
        VehiclePatch: {
            name?: string;
            nickname?: string;
            make?: string;
            model?: string;
            year?: number;
            license_plate?: string;
            vin?: string;
            color?: string;
            fuel_type?: components["schemas"]["FuelType"];
            mileage?: number;
            /** @enum {string} */
            mileage_unit?: "mi" | "km";
            /** Format: date */
            purchase_date?: string;
            purchase_price?: number;
            /** Format: uuid */
            photo_media_id?: string;
        };
        NextMaintenance: {
            /** Format: uuid */
            plan_item_id?: string;
            name?: string;
            due_mileage?: number | null;
            /** Format: date */
            due_on?: string | null;
            overdue?: boolean;
        } | null;
        Dashboard: {
            vehicle: components["schemas"]["Vehicle"];
            ownership: {
                total_spent: number;
                this_month_spent: number;
                /** @example USD */
                currency?: string;
                services_count: number;
                documents_count: number;
            };
            recent_services: components["schemas"]["ServiceRecordSummary"][];
            next_maintenance?: components["schemas"]["NextMaintenance"];
        };
        ServiceRecordSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            serviced_on?: string;
            title?: string;
            total_cost?: number;
        };
        PlanItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            name: string;
            interval_days?: number | null;
            interval_distance?: number | null;
            next_due_mileage?: number | null;
            /** Format: date */
            next_due_on?: string | null;
            enabled: boolean;
            notes?: string | null;
            catalog_key?: string | null;
        };
        PlanItemWrite: {
            /** Format: uuid */
            id: string;
            name: string;
            interval_days?: number;
            interval_distance?: number;
            notes?: string;
            catalog_key?: string;
            /** @default true */
            enabled: boolean;
        };
        PlanItemPatch: {
            name?: string;
            interval_days?: number | null;
            interval_distance?: number | null;
            notes?: string;
            enabled?: boolean;
        };
        SuggestedPlanItem: {
            catalog_key?: string;
            name?: string;
            interval_days?: number | null;
            interval_distance?: number | null;
            fuel_type?: components["schemas"]["FuelType"];
        };
        ServiceRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            /** Format: date */
            serviced_on: string;
            odometer: number;
            total_cost: number;
            workshop_name?: string | null;
            notes?: string | null;
            /** Format: uuid */
            receipt_media_id?: string | null;
            items: components["schemas"]["ServiceLine"][];
            parts?: components["schemas"]["ServicePart"][];
        };
        ServiceLine: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            plan_item_id?: string | null;
            name: string;
            line_cost?: number | null;
        };
        ServicePart: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            part_id: string;
            name: string;
        };
        ServiceRecordWrite: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            serviced_on: string;
            odometer: number;
            total_cost: number;
            workshop_name?: string;
            notes?: string;
            /** Format: uuid */
            receipt_media_id?: string;
            items: components["schemas"]["ServiceLine"][];
            parts?: components["schemas"]["ServicePart"][];
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            name: string;
            category: components["schemas"]["DocumentCategory"];
            notes?: string | null;
            /** Format: uuid */
            media_id?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        DocumentWrite: {
            /** Format: uuid */
            id: string;
            name: string;
            category: components["schemas"]["DocumentCategory"];
            notes?: string;
            /** Format: uuid */
            media_id?: string;
        };
        DocumentPatch: {
            name?: string;
            category?: components["schemas"]["DocumentCategory"];
            notes?: string;
            /** Format: uuid */
            media_id?: string;
        };
        Part: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            name: string;
            brand?: string | null;
            part_number?: string | null;
            notes?: string | null;
        };
        PartWrite: {
            /** Format: uuid */
            id: string;
            name: string;
            brand?: string;
            part_number?: string;
            notes?: string;
        };
        PartPatch: {
            name?: string;
            brand?: string;
            part_number?: string;
            notes?: string;
        };
        FuelCatalogType: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            /** @enum {string} */
            kind: "liquid" | "electric";
            /** @description e.g. L, gal, kWh */
            unit: string;
        };
        FuelCatalogTypeWrite: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "liquid" | "electric";
            unit: string;
        };
        FuelCatalogTypePatch: {
            name?: string;
            /** @enum {string} */
            kind?: "liquid" | "electric";
            unit?: string;
        };
        FuelLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            vehicle_id: string;
            /** @enum {string} */
            kind: "refuel" | "charge";
            /** Format: uuid */
            fuel_type_id?: string | null;
            fuel_type_name: string;
            unit: string;
            /** Format: date */
            logged_on: string;
            amount: number;
            cost: number;
        };
        FuelLogWrite: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fuel_type_id: string;
            /** Format: date */
            logged_on: string;
            amount: number;
            cost: number;
        };
        FuelLogPatch: {
            /** Format: uuid */
            fuel_type_id?: string;
            /** Format: date */
            logged_on?: string;
            amount?: number;
            cost?: number;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            category: components["schemas"]["ExpenseCategory"];
            amount: number;
            /** Format: date */
            incurred_on: string;
            notes?: string | null;
            /** Format: uuid */
            receipt_media_id?: string | null;
            parts?: components["schemas"]["ExpensePart"][];
        };
        ExpenseWrite: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["ExpenseCategory"];
            amount: number;
            /** Format: date */
            incurred_on: string;
            notes?: string;
            /** Format: uuid */
            receipt_media_id?: string;
            parts?: components["schemas"]["ExpensePart"][];
        };
        ExpensePart: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            part_id: string;
            name: string;
        };
        ExpenseSummary: {
            this_month: number;
            total: number;
            by_category?: {
                category?: components["schemas"]["ExpenseCategory"];
                amount?: number;
                percent?: number;
            }[];
        };
        Notification: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            vehicle_id?: string;
            /** Format: uuid */
            plan_item_id?: string | null;
            title?: string;
            body?: string;
            /** @enum {string} */
            status?: "unread" | "read" | "done" | "dismissed";
            /** @enum {string} */
            due_reason?: "date" | "mileage" | "both";
            /** Format: date-time */
            created_at?: string;
        };
        MediaObject: {
            /** Format: uuid */
            id: string;
            blob_key?: string;
            content_type: string;
            byte_size: number;
            sha256?: string;
            /**
             * Format: uri
             * @description Short-lived; omit in list payloads if unused
             */
            download_url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        SyncPushRequest: {
            operations: components["schemas"]["SyncOperation"][];
        };
        SyncOperation: {
            /** @enum {string} */
            entity_type: "vehicle" | "plan_item" | "service_record" | "document" | "expense" | "notification" | "media" | "part" | "fuel_type" | "fuel_log";
            /** Format: uuid */
            entity_id: string;
            /** @enum {string} */
            op: "upsert" | "archive" | "delete";
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            client_ts: string;
        };
        SyncPushResponse: {
            results?: {
                /** Format: uuid */
                entity_id?: string;
                /** @enum {string} */
                status?: "applied" | "idempotent" | "conflict" | "rejected";
                /** Format: date-time */
                server_ts?: string;
                error?: components["schemas"]["ErrorBody"];
            }[];
        };
        SyncPullResponse: {
            /** @description Opaque next cursor */
            cursor: string;
            changes: {
                entity_type?: string;
                /** Format: uuid */
                entity_id?: string;
                /** @enum {string} */
                op?: "upsert" | "archive" | "delete";
                payload?: Record<string, never>;
                /** Format: date-time */
                server_ts?: string;
            }[];
        };
        AdminDashboard: {
            users_total?: number;
            vehicles_active?: number;
            partners_total?: number;
            sync_errors_24h?: number;
            recent_activity?: {
                /** Format: date-time */
                at?: string;
                /** @enum {string} */
                kind?: "signup" | "vehicle_added" | "sync_error" | "partner_status";
                summary?: string;
            }[];
        };
        AdminUserListItem: {
            /** Format: uuid */
            id?: string;
            email?: string;
            display_name?: string | null;
            plan?: components["schemas"]["Plan"];
            status?: components["schemas"]["AccountStatus"];
            vehicle_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        AdminUserProfile: components["schemas"]["AdminUserListItem"] & {
            email_verified?: boolean;
            vehicles?: {
                /** Format: uuid */
                id?: string;
                nickname?: string;
                license_plate?: string;
            }[];
            /** @description Metadata count only */
            documents_count?: number;
        };
        Partner: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["PartnerType"];
            status: components["schemas"]["PartnerStatus"];
            contact_email?: string | null;
            contact_phone?: string | null;
            notes?: string | null;
            /** Format: date-time */
            updated_at?: string;
        };
        PartnerWrite: {
            name: string;
            type: components["schemas"]["PartnerType"];
            status?: components["schemas"]["PartnerStatus"];
            contact_email?: string;
            contact_phone?: string;
            notes?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        vehicleId: string;
        planItemId: string;
        serviceRecordId: string;
        documentId: string;
        expenseId: string;
        notificationId: string;
        mediaId: string;
        userId: string;
        partnerId: string;
        partId: string;
        fuelTypeId: string;
        fuelLogId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
